on:
  push:
    branches:
      - master

jobs:
  build:
    name: merge to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: create a release
        uses: extenda/actions/conventional-release@v0
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          TAG_PREFIX: v
